name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      run: |
        sh <(curl -L https://nixos.org/nix/install) --no-daemon
        mkdir $HOME/.config/nix
        echo "experimental-features = nix-command flakes" >> $HOME/.config/nix/nix.conf
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH
        source $HOME/.nix-profile/etc/profile.d/nix.sh


    - name: Install home-manager
      run: |
        nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
        nix-channel --update
        nix-shell '<home-manager>' -A install
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH
        source $HOME/.nix-profile/etc/profile.d/nix.sh

    - name: Run home-manager
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
